// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortChatWithAgent() {
  return window['go']['main']['App']['AbortChatWithAgent']();
}

export function AbortSummaryStockNews() {
  return window['go']['main']['App']['AbortSummaryStockNews']();
}

export function ActivateQuantTemplate(arg1) {
  return window['go']['main']['App']['ActivateQuantTemplate'](arg1);
}

export function AddAllStockInfo(arg1) {
  return window['go']['main']['App']['AddAllStockInfo'](arg1);
}

export function AddCronTask(arg1) {
  return window['go']['main']['App']['AddCronTask'](arg1);
}

export function AddGroup(arg1) {
  return window['go']['main']['App']['AddGroup'](arg1);
}

export function AddPrompt(arg1) {
  return window['go']['main']['App']['AddPrompt'](arg1);
}

export function AddPromptTemplate(arg1) {
  return window['go']['main']['App']['AddPromptTemplate'](arg1);
}

export function AddStockGroup(arg1, arg2) {
  return window['go']['main']['App']['AddStockGroup'](arg1, arg2);
}

export function AddTradingRecord(arg1) {
  return window['go']['main']['App']['AddTradingRecord'](arg1);
}

export function AddTransaction(arg1) {
  return window['go']['main']['App']['AddTransaction'](arg1);
}

export function AnalyzeBetterFundsWithAI(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AnalyzeBetterFundsWithAI'](arg1, arg2, arg3, arg4);
}

export function AnalyzeFundCollectionWithAI(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AnalyzeFundCollectionWithAI'](arg1, arg2, arg3, arg4, arg5);
}

export function AnalyzeFundWithAI(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeFundWithAI'](arg1, arg2, arg3);
}

export function AnalyzeQuantLinkageWithAI(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeQuantLinkageWithAI'](arg1, arg2);
}

export function AnalyzeSentiment(arg1) {
  return window['go']['main']['App']['AnalyzeSentiment'](arg1);
}

export function AnalyzeSentimentWithFreqWeight(arg1) {
  return window['go']['main']['App']['AnalyzeSentimentWithFreqWeight'](arg1);
}

export function BatchDeleteAllStockInfo(arg1) {
  return window['go']['main']['App']['BatchDeleteAllStockInfo'](arg1);
}

export function BuildQuantPrompt(arg1) {
  return window['go']['main']['App']['BuildQuantPrompt'](arg1);
}

export function BuildQuantScriptSearchLinks(arg1) {
  return window['go']['main']['App']['BuildQuantScriptSearchLinks'](arg1);
}

export function CalculateNextRunTime(arg1) {
  return window['go']['main']['App']['CalculateNextRunTime'](arg1);
}

export function CalculateNextRunTimes(arg1, arg2) {
  return window['go']['main']['App']['CalculateNextRunTimes'](arg1, arg2);
}

export function ChatWithAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatWithAgent'](arg1, arg2, arg3);
}

export function ChatWithHouseholdDigitalAnalysis(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChatWithHouseholdDigitalAnalysis'](arg1, arg2, arg3, arg4);
}

export function CheckDeviceBinding(arg1, arg2) {
  return window['go']['main']['App']['CheckDeviceBinding'](arg1, arg2);
}

export function CheckFrequentTrading(arg1) {
  return window['go']['main']['App']['CheckFrequentTrading'](arg1);
}

export function CheckSponsorCode(arg1) {
  return window['go']['main']['App']['CheckSponsorCode'](arg1);
}

export function CheckStockBaseInfo(arg1) {
  return window['go']['main']['App']['CheckStockBaseInfo'](arg1);
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function ClsCalendar() {
  return window['go']['main']['App']['ClsCalendar']();
}

export function CompareFunds(arg1) {
  return window['go']['main']['App']['CompareFunds'](arg1);
}

export function CreateAsset(arg1) {
  return window['go']['main']['App']['CreateAsset'](arg1);
}

export function CreateAssetCategory(arg1) {
  return window['go']['main']['App']['CreateAssetCategory'](arg1);
}

export function CreateCronTask(arg1) {
  return window['go']['main']['App']['CreateCronTask'](arg1);
}

export function CreateHolding(arg1) {
  return window['go']['main']['App']['CreateHolding'](arg1);
}

export function CreateHouseholdAccount(arg1) {
  return window['go']['main']['App']['CreateHouseholdAccount'](arg1);
}

export function CreateHouseholdFixedAsset(arg1) {
  return window['go']['main']['App']['CreateHouseholdFixedAsset'](arg1);
}

export function CreateHouseholdIncome(arg1) {
  return window['go']['main']['App']['CreateHouseholdIncome'](arg1);
}

export function CreateHouseholdLiability(arg1) {
  return window['go']['main']['App']['CreateHouseholdLiability'](arg1);
}

export function CreateHouseholdMember(arg1) {
  return window['go']['main']['App']['CreateHouseholdMember'](arg1);
}

export function CreateHouseholdProtection(arg1) {
  return window['go']['main']['App']['CreateHouseholdProtection'](arg1);
}

export function CreateMCPServer(arg1) {
  return window['go']['main']['App']['CreateMCPServer'](arg1);
}

export function CreateQuantCategory(arg1) {
  return window['go']['main']['App']['CreateQuantCategory'](arg1);
}

export function CreateQuantTemplate(arg1) {
  return window['go']['main']['App']['CreateQuantTemplate'](arg1);
}

export function CreateSkill(arg1) {
  return window['go']['main']['App']['CreateSkill'](arg1);
}

export function DelPrompt(arg1) {
  return window['go']['main']['App']['DelPrompt'](arg1);
}

export function DeleteAIResponseResult(arg1) {
  return window['go']['main']['App']['DeleteAIResponseResult'](arg1);
}

export function DeleteAiRecommendStocks(arg1) {
  return window['go']['main']['App']['DeleteAiRecommendStocks'](arg1);
}

export function DeleteAllStockInfo(arg1) {
  return window['go']['main']['App']['DeleteAllStockInfo'](arg1);
}

export function DeleteAsset(arg1) {
  return window['go']['main']['App']['DeleteAsset'](arg1);
}

export function DeleteCronTask(arg1) {
  return window['go']['main']['App']['DeleteCronTask'](arg1);
}

export function DeleteCustomStrategy(arg1) {
  return window['go']['main']['App']['DeleteCustomStrategy'](arg1);
}

export function DeleteFundWatchGroup(arg1) {
  return window['go']['main']['App']['DeleteFundWatchGroup'](arg1);
}

export function DeleteHolding(arg1) {
  return window['go']['main']['App']['DeleteHolding'](arg1);
}

export function DeleteHouseholdAccount(arg1) {
  return window['go']['main']['App']['DeleteHouseholdAccount'](arg1);
}

export function DeleteHouseholdBenchmark(arg1) {
  return window['go']['main']['App']['DeleteHouseholdBenchmark'](arg1);
}

export function DeleteHouseholdFixedAsset(arg1) {
  return window['go']['main']['App']['DeleteHouseholdFixedAsset'](arg1);
}

export function DeleteHouseholdIncome(arg1) {
  return window['go']['main']['App']['DeleteHouseholdIncome'](arg1);
}

export function DeleteHouseholdLiability(arg1) {
  return window['go']['main']['App']['DeleteHouseholdLiability'](arg1);
}

export function DeleteHouseholdMember(arg1) {
  return window['go']['main']['App']['DeleteHouseholdMember'](arg1);
}

export function DeleteHouseholdProtection(arg1) {
  return window['go']['main']['App']['DeleteHouseholdProtection'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function DeletePromptTemplate(arg1) {
  return window['go']['main']['App']['DeletePromptTemplate'](arg1);
}

export function DeleteQuantTemplate(arg1) {
  return window['go']['main']['App']['DeleteQuantTemplate'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function DeleteStockChangeHistory(arg1) {
  return window['go']['main']['App']['DeleteStockChangeHistory'](arg1);
}

export function DeleteTradingRecord(arg1) {
  return window['go']['main']['App']['DeleteTradingRecord'](arg1);
}

export function EMDictCode(arg1) {
  return window['go']['main']['App']['EMDictCode'](arg1);
}

export function EnableCronTask(arg1, arg2) {
  return window['go']['main']['App']['EnableCronTask'](arg1, arg2);
}

export function EnableMCPServer(arg1, arg2) {
  return window['go']['main']['App']['EnableMCPServer'](arg1, arg2);
}

export function EnableSkill(arg1, arg2) {
  return window['go']['main']['App']['EnableSkill'](arg1, arg2);
}

export function EnsureFundUniverse() {
  return window['go']['main']['App']['EnsureFundUniverse']();
}

export function ExecuteCronTaskNow(arg1) {
  return window['go']['main']['App']['ExecuteCronTaskNow'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function ExportQuantTemplate(arg1) {
  return window['go']['main']['App']['ExportQuantTemplate'](arg1);
}

export function FetchAiModelInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchAiModelInfo'](arg1, arg2, arg3);
}

export function FetchAiModels(arg1, arg2) {
  return window['go']['main']['App']['FetchAiModels'](arg1, arg2);
}

export function FetchAndSaveMarketStatistic() {
  return window['go']['main']['App']['FetchAndSaveMarketStatistic']();
}

export function FetchBKFundFlowNow() {
  return window['go']['main']['App']['FetchBKFundFlowNow']();
}

export function FetchConceptFundFlowNow() {
  return window['go']['main']['App']['FetchConceptFundFlowNow']();
}

export function Follow(arg1) {
  return window['go']['main']['App']['Follow'](arg1);
}

export function FollowFund(arg1) {
  return window['go']['main']['App']['FollowFund'](arg1);
}

export function GenerateQuantCode(arg1, arg2) {
  return window['go']['main']['App']['GenerateQuantCode'](arg1, arg2);
}

export function GetAIResponseResult(arg1) {
  return window['go']['main']['App']['GetAIResponseResult'](arg1);
}

export function GetAIResponseResultList(arg1) {
  return window['go']['main']['App']['GetAIResponseResultList'](arg1);
}

export function GetAiAssistantSession(arg1) {
  return window['go']['main']['App']['GetAiAssistantSession'](arg1);
}

export function GetAiConfigs() {
  return window['go']['main']['App']['GetAiConfigs']();
}

export function GetAiRecommendStocksList(arg1) {
  return window['go']['main']['App']['GetAiRecommendStocksList'](arg1);
}

export function GetAllBKCodes() {
  return window['go']['main']['App']['GetAllBKCodes']();
}

export function GetAllConceptCodes() {
  return window['go']['main']['App']['GetAllConceptCodes']();
}

export function GetAllConcepts() {
  return window['go']['main']['App']['GetAllConcepts']();
}

export function GetAllCustomStrategies() {
  return window['go']['main']['App']['GetAllCustomStrategies']();
}

export function GetAllGroupStocks() {
  return window['go']['main']['App']['GetAllGroupStocks']();
}

export function GetAllHoldings() {
  return window['go']['main']['App']['GetAllHoldings']();
}

export function GetAllIndustries() {
  return window['go']['main']['App']['GetAllIndustries']();
}

export function GetAllMCPTools() {
  return window['go']['main']['App']['GetAllMCPTools']();
}

export function GetAllMarkets() {
  return window['go']['main']['App']['GetAllMarkets']();
}

export function GetAllSkills() {
  return window['go']['main']['App']['GetAllSkills']();
}

export function GetAllStockChangesWithPaging(arg1) {
  return window['go']['main']['App']['GetAllStockChangesWithPaging'](arg1);
}

export function GetAllStockInfoById(arg1) {
  return window['go']['main']['App']['GetAllStockInfoById'](arg1);
}

export function GetAllStockInfoList(arg1) {
  return window['go']['main']['App']['GetAllStockInfoList'](arg1);
}

export function GetAllStocks(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAllStocks'](arg1, arg2, arg3, arg4);
}

export function GetAssetCategories() {
  return window['go']['main']['App']['GetAssetCategories']();
}

export function GetAssetSummary() {
  return window['go']['main']['App']['GetAssetSummary']();
}

export function GetAssets() {
  return window['go']['main']['App']['GetAssets']();
}

export function GetAssetsByType(arg1) {
  return window['go']['main']['App']['GetAssetsByType'](arg1);
}

export function GetBKFundFlowListByDate(arg1, arg2) {
  return window['go']['main']['App']['GetBKFundFlowListByDate'](arg1, arg2);
}

export function GetBKFundFlowTopListByDate(arg1, arg2) {
  return window['go']['main']['App']['GetBKFundFlowTopListByDate'](arg1, arg2);
}

export function GetBetterFunds(arg1) {
  return window['go']['main']['App']['GetBetterFunds'](arg1);
}

export function GetChangeRank(arg1, arg2) {
  return window['go']['main']['App']['GetChangeRank'](arg1, arg2);
}

export function GetChangeTypeDailyStats(arg1) {
  return window['go']['main']['App']['GetChangeTypeDailyStats'](arg1);
}

export function GetChipDistribution(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetChipDistribution'](arg1, arg2, arg3, arg4);
}

export function GetConceptFundFlowListByDate(arg1, arg2) {
  return window['go']['main']['App']['GetConceptFundFlowListByDate'](arg1, arg2);
}

export function GetConceptFundFlowTopListByDate(arg1, arg2) {
  return window['go']['main']['App']['GetConceptFundFlowTopListByDate'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCronTaskByID(arg1) {
  return window['go']['main']['App']['GetCronTaskByID'](arg1);
}

export function GetCronTaskList(arg1) {
  return window['go']['main']['App']['GetCronTaskList'](arg1);
}

export function GetCronTaskTypes() {
  return window['go']['main']['App']['GetCronTaskTypes']();
}

export function GetDailyChangeStats(arg1) {
  return window['go']['main']['App']['GetDailyChangeStats'](arg1);
}

export function GetDailyDimensionStats(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDailyDimensionStats'](arg1, arg2, arg3);
}

export function GetEffectiveSponsorVip() {
  return window['go']['main']['App']['GetEffectiveSponsorVip']();
}

export function GetFollowList(arg1) {
  return window['go']['main']['App']['GetFollowList'](arg1);
}

export function GetFollowedFund() {
  return window['go']['main']['App']['GetFollowedFund']();
}

export function GetFollowedFundPaged(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFollowedFundPaged'](arg1, arg2, arg3);
}

export function GetFundEstimateSourcePreference() {
  return window['go']['main']['App']['GetFundEstimateSourcePreference']();
}

export function GetFundHistoryNetValue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFundHistoryNetValue'](arg1, arg2, arg3, arg4);
}

export function GetFundKLine(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetFundKLine'](arg1, arg2, arg3);
}

export function GetFundPortfolioDashboard() {
  return window['go']['main']['App']['GetFundPortfolioDashboard']();
}

export function GetFundPortfolioDashboardByFundEstimateSource(arg1) {
  return window['go']['main']['App']['GetFundPortfolioDashboardByFundEstimateSource'](arg1);
}

export function GetFundProfile(arg1) {
  return window['go']['main']['App']['GetFundProfile'](arg1);
}

export function GetFundProfileByFundEstimateSource(arg1, arg2) {
  return window['go']['main']['App']['GetFundProfileByFundEstimateSource'](arg1, arg2);
}

export function GetFundRanking(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetFundRanking'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetFundRecommendationRefreshStatus(arg1) {
  return window['go']['main']['App']['GetFundRecommendationRefreshStatus'](arg1);
}

export function GetFundScreener(arg1) {
  return window['go']['main']['App']['GetFundScreener'](arg1);
}

export function GetFundTop10Holdings(arg1) {
  return window['go']['main']['App']['GetFundTop10Holdings'](arg1);
}

export function GetGroupList() {
  return window['go']['main']['App']['GetGroupList']();
}

export function GetGroupStockList(arg1) {
  return window['go']['main']['App']['GetGroupStockList'](arg1);
}

export function GetHoldingsByType(arg1) {
  return window['go']['main']['App']['GetHoldingsByType'](arg1);
}

export function GetHotStrategy() {
  return window['go']['main']['App']['GetHotStrategy']();
}

export function GetHouseholdAccounts() {
  return window['go']['main']['App']['GetHouseholdAccounts']();
}

export function GetHouseholdBenchmarks(arg1) {
  return window['go']['main']['App']['GetHouseholdBenchmarks'](arg1);
}

export function GetHouseholdDashboardSummary() {
  return window['go']['main']['App']['GetHouseholdDashboardSummary']();
}

export function GetHouseholdFixedAssets() {
  return window['go']['main']['App']['GetHouseholdFixedAssets']();
}

export function GetHouseholdIncomes() {
  return window['go']['main']['App']['GetHouseholdIncomes']();
}

export function GetHouseholdLiabilities() {
  return window['go']['main']['App']['GetHouseholdLiabilities']();
}

export function GetHouseholdLiabilitySchedules(arg1) {
  return window['go']['main']['App']['GetHouseholdLiabilitySchedules'](arg1);
}

export function GetHouseholdLiabilityTrend(arg1, arg2) {
  return window['go']['main']['App']['GetHouseholdLiabilityTrend'](arg1, arg2);
}

export function GetHouseholdLiquidAssetDistribution() {
  return window['go']['main']['App']['GetHouseholdLiquidAssetDistribution']();
}

export function GetHouseholdLiquidAssetTrend(arg1) {
  return window['go']['main']['App']['GetHouseholdLiquidAssetTrend'](arg1);
}

export function GetHouseholdMembers() {
  return window['go']['main']['App']['GetHouseholdMembers']();
}

export function GetHouseholdProfile() {
  return window['go']['main']['App']['GetHouseholdProfile']();
}

export function GetHouseholdProtections() {
  return window['go']['main']['App']['GetHouseholdProtections']();
}

export function GetHouseholdSnapshots(arg1) {
  return window['go']['main']['App']['GetHouseholdSnapshots'](arg1);
}

export function GetIndustryMoneyRankSina(arg1, arg2) {
  return window['go']['main']['App']['GetIndustryMoneyRankSina'](arg1, arg2);
}

export function GetIndustryRank(arg1, arg2) {
  return window['go']['main']['App']['GetIndustryRank'](arg1, arg2);
}

export function GetLatestHouseholdAIAnalysis() {
  return window['go']['main']['App']['GetLatestHouseholdAIAnalysis']();
}

export function GetLatestPortfolioExpectationAIAnalysis() {
  return window['go']['main']['App']['GetLatestPortfolioExpectationAIAnalysis']();
}

export function GetLatestTradingDay() {
  return window['go']['main']['App']['GetLatestTradingDay']();
}

export function GetMCPServerByID(arg1) {
  return window['go']['main']['App']['GetMCPServerByID'](arg1);
}

export function GetMCPServerList(arg1) {
  return window['go']['main']['App']['GetMCPServerList'](arg1);
}

export function GetMCPToolsByServerID(arg1) {
  return window['go']['main']['App']['GetMCPToolsByServerID'](arg1);
}

export function GetMachineId() {
  return window['go']['main']['App']['GetMachineId']();
}

export function GetMarketStatisticByDate(arg1) {
  return window['go']['main']['App']['GetMarketStatisticByDate'](arg1);
}

export function GetMoneyRankSina(arg1) {
  return window['go']['main']['App']['GetMoneyRankSina'](arg1);
}

export function GetPortfolioExpectationSummary() {
  return window['go']['main']['App']['GetPortfolioExpectationSummary']();
}

export function GetPortfolioSummary() {
  return window['go']['main']['App']['GetPortfolioSummary']();
}

export function GetProfitHistory(arg1) {
  return window['go']['main']['App']['GetProfitHistory'](arg1);
}

export function GetPromptTemplateList(arg1) {
  return window['go']['main']['App']['GetPromptTemplateList'](arg1);
}

export function GetPromptTemplates(arg1, arg2) {
  return window['go']['main']['App']['GetPromptTemplates'](arg1, arg2);
}

export function GetQuantCategories() {
  return window['go']['main']['App']['GetQuantCategories']();
}

export function GetQuantTagTaxonomy() {
  return window['go']['main']['App']['GetQuantTagTaxonomy']();
}

export function GetQuantTemplate(arg1) {
  return window['go']['main']['App']['GetQuantTemplate'](arg1);
}

export function GetQuantTemplates(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetQuantTemplates'](arg1, arg2, arg3, arg4);
}

export function GetRecentDaysMarketStatistic(arg1) {
  return window['go']['main']['App']['GetRecentDaysMarketStatistic'](arg1);
}

export function GetSkillByID(arg1) {
  return window['go']['main']['App']['GetSkillByID'](arg1);
}

export function GetSkillList(arg1) {
  return window['go']['main']['App']['GetSkillList'](arg1);
}

export function GetSponsorInfo() {
  return window['go']['main']['App']['GetSponsorInfo']();
}

export function GetStockChangeHistory(arg1) {
  return window['go']['main']['App']['GetStockChangeHistory'](arg1);
}

export function GetStockChanges(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStockChanges'](arg1, arg2, arg3);
}

export function GetStockCommonKLine(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStockCommonKLine'](arg1, arg2, arg3);
}

export function GetStockEastMoneyKLine(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetStockEastMoneyKLine'](arg1, arg2, arg3, arg4);
}

export function GetStockEastMoneyKLinePage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetStockEastMoneyKLinePage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStockKLine(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStockKLine'](arg1, arg2, arg3);
}

export function GetStockKLinePageWithFallback(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['GetStockKLinePageWithFallback'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetStockKLineWithFallback(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetStockKLineWithFallback'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStockList(arg1) {
  return window['go']['main']['App']['GetStockList'](arg1);
}

export function GetStockMinutePriceLineData(arg1, arg2) {
  return window['go']['main']['App']['GetStockMinutePriceLineData'](arg1, arg2);
}

export function GetStockMoneyTrendByDay(arg1, arg2) {
  return window['go']['main']['App']['GetStockMoneyTrendByDay'](arg1, arg2);
}

export function GetStockRealTimePrice(arg1) {
  return window['go']['main']['App']['GetStockRealTimePrice'](arg1);
}

export function GetTdxCallAuction(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTdxCallAuction'](arg1, arg2, arg3);
}

export function GetTdxCompanyCategoryContent(arg1, arg2) {
  return window['go']['main']['App']['GetTdxCompanyCategoryContent'](arg1, arg2);
}

export function GetTdxCompanyCategoryList(arg1) {
  return window['go']['main']['App']['GetTdxCompanyCategoryList'](arg1);
}

export function GetTdxCompanyInfo(arg1) {
  return window['go']['main']['App']['GetTdxCompanyInfo'](arg1);
}

export function GetTdxFinanceInfo(arg1) {
  return window['go']['main']['App']['GetTdxFinanceInfo'](arg1);
}

export function GetTdxSymbolBelongBoard(arg1) {
  return window['go']['main']['App']['GetTdxSymbolBelongBoard'](arg1);
}

export function GetTdxXDXRInfo(arg1) {
  return window['go']['main']['App']['GetTdxXDXRInfo'](arg1);
}

export function GetTelegraphList(arg1) {
  return window['go']['main']['App']['GetTelegraphList'](arg1);
}

export function GetTodayMarketStatistic() {
  return window['go']['main']['App']['GetTodayMarketStatistic']();
}

export function GetTradingRecordList(arg1) {
  return window['go']['main']['App']['GetTradingRecordList'](arg1);
}

export function GetTradingRecordStatistics() {
  return window['go']['main']['App']['GetTradingRecordStatistics']();
}

export function GetTransactions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTransactions'](arg1, arg2, arg3);
}

export function GetTypeStatsByDate(arg1) {
  return window['go']['main']['App']['GetTypeStatsByDate'](arg1);
}

export function GetUplimitHot(arg1, arg2) {
  return window['go']['main']['App']['GetUplimitHot'](arg1, arg2);
}

export function GetUserManual() {
  return window['go']['main']['App']['GetUserManual']();
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function GetfundList(arg1) {
  return window['go']['main']['App']['GetfundList'](arg1);
}

export function GlobalStockIndexes() {
  return window['go']['main']['App']['GlobalStockIndexes']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HotEvent(arg1) {
  return window['go']['main']['App']['HotEvent'](arg1);
}

export function HotStock(arg1) {
  return window['go']['main']['App']['HotStock'](arg1);
}

export function HotTopic(arg1) {
  return window['go']['main']['App']['HotTopic'](arg1);
}

export function IndustryResearchReport(arg1) {
  return window['go']['main']['App']['IndustryResearchReport'](arg1);
}

export function InitCronTasks() {
  return window['go']['main']['App']['InitCronTasks']();
}

export function InitializeGroupSort() {
  return window['go']['main']['App']['InitializeGroupSort']();
}

export function InvestCalendarTimeLine(arg1) {
  return window['go']['main']['App']['InvestCalendarTimeLine'](arg1);
}

export function IsHKTradingTime() {
  return window['go']['main']['App']['IsHKTradingTime']();
}

export function IsTradingDay(arg1) {
  return window['go']['main']['App']['IsTradingDay'](arg1);
}

export function IsTradingTime() {
  return window['go']['main']['App']['IsTradingTime']();
}

export function IsUSTradingTime() {
  return window['go']['main']['App']['IsUSTradingTime']();
}

export function LongTigerRank(arg1) {
  return window['go']['main']['App']['LongTigerRank'](arg1);
}

export function NewChatStream(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['NewChatStream'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function NewsPush(arg1) {
  return window['go']['main']['App']['NewsPush'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PromptPlazaRequest(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PromptPlazaRequest'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReFleshTelegraphList(arg1) {
  return window['go']['main']['App']['ReFleshTelegraphList'](arg1);
}

export function RebuildHouseholdLiabilitySchedule(arg1) {
  return window['go']['main']['App']['RebuildHouseholdLiabilitySchedule'](arg1);
}

export function RefreshFundProfile(arg1) {
  return window['go']['main']['App']['RefreshFundProfile'](arg1);
}

export function RefreshFundProfileByFundEstimateSource(arg1, arg2) {
  return window['go']['main']['App']['RefreshFundProfileByFundEstimateSource'](arg1, arg2);
}

export function RefreshFundScreenerData(arg1) {
  return window['go']['main']['App']['RefreshFundScreenerData'](arg1);
}

export function RemoveGroup(arg1) {
  return window['go']['main']['App']['RemoveGroup'](arg1);
}

export function RemoveStockGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveStockGroup'](arg1, arg2, arg3);
}

export function RenameFundWatchGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameFundWatchGroup'](arg1, arg2);
}

export function RestartAsAdmin() {
  return window['go']['main']['App']['RestartAsAdmin']();
}

export function RunHouseholdAIAnalysis(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunHouseholdAIAnalysis'](arg1, arg2, arg3, arg4);
}

export function RunPortfolioExpectationAIAnalysis(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunPortfolioExpectationAIAnalysis'](arg1, arg2, arg3);
}

export function SaveAIResponseResult(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveAIResponseResult'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveAiAssistantSession(arg1, arg2) {
  return window['go']['main']['App']['SaveAiAssistantSession'](arg1, arg2);
}

export function SaveAsMarkdown(arg1, arg2) {
  return window['go']['main']['App']['SaveAsMarkdown'](arg1, arg2);
}

export function SaveCustomStrategy(arg1) {
  return window['go']['main']['App']['SaveCustomStrategy'](arg1);
}

export function SaveFundEstimateSourcePreference(arg1) {
  return window['go']['main']['App']['SaveFundEstimateSourcePreference'](arg1);
}

export function SaveHouseholdSnapshot(arg1) {
  return window['go']['main']['App']['SaveHouseholdSnapshot'](arg1);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SavePortfolioSnapshot() {
  return window['go']['main']['App']['SavePortfolioSnapshot']();
}

export function SaveStockChangesToHistory(arg1) {
  return window['go']['main']['App']['SaveStockChangesToHistory'](arg1);
}

export function SaveWordFile(arg1, arg2) {
  return window['go']['main']['App']['SaveWordFile'](arg1, arg2);
}

export function SearchCronTasks(arg1) {
  return window['go']['main']['App']['SearchCronTasks'](arg1);
}

export function SearchFundCodes(arg1) {
  return window['go']['main']['App']['SearchFundCodes'](arg1);
}

export function SearchQuantScriptsWithAI(arg1, arg2) {
  return window['go']['main']['App']['SearchQuantScriptsWithAI'](arg1, arg2);
}

export function SearchStock(arg1) {
  return window['go']['main']['App']['SearchStock'](arg1);
}

export function SendDingDingMessage(arg1, arg2) {
  return window['go']['main']['App']['SendDingDingMessage'](arg1, arg2);
}

export function SendDingDingMessageByType(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendDingDingMessageByType'](arg1, arg2, arg3);
}

export function SendFeishuMessage(arg1, arg2) {
  return window['go']['main']['App']['SendFeishuMessage'](arg1, arg2);
}

export function SendFeishuMessageByType(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendFeishuMessageByType'](arg1, arg2, arg3);
}

export function SendLocalNotification(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendLocalNotification'](arg1, arg2, arg3);
}

export function SetAlarmChangePercent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAlarmChangePercent'](arg1, arg2, arg3);
}

export function SetCostPriceAndVolume(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCostPriceAndVolume'](arg1, arg2, arg3);
}

export function SetStockAICron(arg1, arg2) {
  return window['go']['main']['App']['SetStockAICron'](arg1, arg2);
}

export function SetStockSort(arg1, arg2) {
  return window['go']['main']['App']['SetStockSort'](arg1, arg2);
}

export function SetTradingPrice(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetTradingPrice'](arg1, arg2, arg3, arg4, arg5);
}

export function ShareAnalysis(arg1, arg2) {
  return window['go']['main']['App']['ShareAnalysis'](arg1, arg2);
}

export function ShareText(arg1, arg2) {
  return window['go']['main']['App']['ShareText'](arg1, arg2);
}

export function StockNotice(arg1) {
  return window['go']['main']['App']['StockNotice'](arg1);
}

export function StockResearchReport(arg1) {
  return window['go']['main']['App']['StockResearchReport'](arg1);
}

export function SummaryStockNews(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SummaryStockNews'](arg1, arg2, arg3, arg4, arg5);
}

export function SyncPortfolioQuotes() {
  return window['go']['main']['App']['SyncPortfolioQuotes']();
}

export function SyncPortfolioQuotesByFundEstimateSource(arg1) {
  return window['go']['main']['App']['SyncPortfolioQuotesByFundEstimateSource'](arg1);
}

export function TestAIConfigConnection(arg1) {
  return window['go']['main']['App']['TestAIConfigConnection'](arg1);
}

export function TestMCPServer(arg1) {
  return window['go']['main']['App']['TestMCPServer'](arg1);
}

export function UnFollow(arg1) {
  return window['go']['main']['App']['UnFollow'](arg1);
}

export function UnFollowFund(arg1) {
  return window['go']['main']['App']['UnFollowFund'](arg1);
}

export function UpdateAiRecommendStocksAlert(arg1, arg2) {
  return window['go']['main']['App']['UpdateAiRecommendStocksAlert'](arg1, arg2);
}

export function UpdateAsset(arg1) {
  return window['go']['main']['App']['UpdateAsset'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateCronTask(arg1) {
  return window['go']['main']['App']['UpdateCronTask'](arg1);
}

export function UpdateFundWatchGroup(arg1, arg2) {
  return window['go']['main']['App']['UpdateFundWatchGroup'](arg1, arg2);
}

export function UpdateGroup(arg1, arg2) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2);
}

export function UpdateGroupSort(arg1, arg2) {
  return window['go']['main']['App']['UpdateGroupSort'](arg1, arg2);
}

export function UpdateHolding(arg1) {
  return window['go']['main']['App']['UpdateHolding'](arg1);
}

export function UpdateHouseholdAccount(arg1) {
  return window['go']['main']['App']['UpdateHouseholdAccount'](arg1);
}

export function UpdateHouseholdFixedAsset(arg1) {
  return window['go']['main']['App']['UpdateHouseholdFixedAsset'](arg1);
}

export function UpdateHouseholdIncome(arg1) {
  return window['go']['main']['App']['UpdateHouseholdIncome'](arg1);
}

export function UpdateHouseholdLiability(arg1) {
  return window['go']['main']['App']['UpdateHouseholdLiability'](arg1);
}

export function UpdateHouseholdMember(arg1) {
  return window['go']['main']['App']['UpdateHouseholdMember'](arg1);
}

export function UpdateHouseholdProtection(arg1) {
  return window['go']['main']['App']['UpdateHouseholdProtection'](arg1);
}

export function UpdateMCPServer(arg1) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1);
}

export function UpdatePromptTemplate(arg1) {
  return window['go']['main']['App']['UpdatePromptTemplate'](arg1);
}

export function UpdateQuantTemplate(arg1) {
  return window['go']['main']['App']['UpdateQuantTemplate'](arg1);
}

export function UpdateSkill(arg1) {
  return window['go']['main']['App']['UpdateSkill'](arg1);
}

export function UpdateTradingRecord(arg1) {
  return window['go']['main']['App']['UpdateTradingRecord'](arg1);
}

export function UpsertFundHoldingByAmount(arg1) {
  return window['go']['main']['App']['UpsertFundHoldingByAmount'](arg1);
}

export function UpsertHouseholdBenchmark(arg1) {
  return window['go']['main']['App']['UpsertHouseholdBenchmark'](arg1);
}

export function UpsertHouseholdProfile(arg1) {
  return window['go']['main']['App']['UpsertHouseholdProfile'](arg1);
}

export function ValidateCronExpr(arg1) {
  return window['go']['main']['App']['ValidateCronExpr'](arg1);
}

export function VerifyAssetUnlockPassword(arg1) {
  return window['go']['main']['App']['VerifyAssetUnlockPassword'](arg1);
}
