// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {data} from '../models';
import {portfolio} from '../models';
import {quant} from '../models';
import {asset} from '../models';

export function ActivateQuantTemplate(arg1:number):Promise<boolean>;

export function AddAllStockInfo(arg1:models.AllStockInfo):Promise<string>;

export function AddGroup(arg1:data.Group):Promise<string>;

export function AddPrompt(arg1:models.PromptTemplate):Promise<string>;

export function AddPromptTemplate(arg1:models.PromptTemplate):Promise<string>;

export function AddStockGroup(arg1:number,arg2:string):Promise<string>;

export function AddTransaction(arg1:portfolio.Transaction):Promise<portfolio.Transaction>;

export function AnalyzeBetterFundsWithAI(arg1:portfolio.BetterFundQuery,arg2:number,arg3:number,arg4:number):Promise<Record<string, any>>;

export function AnalyzeFundCollectionWithAI(arg1:string,arg2:string,arg3:Array<string>,arg4:number,arg5:number):Promise<Record<string, any>>;

export function AnalyzeFundWithAI(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function AnalyzeQuantLinkageWithAI(arg1:quant.LinkageAIRequest,arg2:number):Promise<Record<string, any>>;

export function AnalyzeSentiment(arg1:string):Promise<models.SentimentResult>;

export function AnalyzeSentimentWithFreqWeight(arg1:string):Promise<Record<string, any>>;

export function BatchDeleteAllStockInfo(arg1:Array<number>):Promise<string>;

export function BuildQuantPrompt(arg1:quant.GenerateRequest):Promise<string>;

export function BuildQuantScriptSearchLinks(arg1:string):Promise<Array<quant.SearchLink>>;

export function ChatWithAgent(arg1:string,arg2:number,arg3:any):Promise<void>;

export function ChatWithHouseholdDigitalAnalysis(arg1:string,arg2:number,arg3:number,arg4:Array<asset.HouseholdChatMessage>):Promise<Record<string, any>>;

export function CheckSponsorCode(arg1:string):Promise<Record<string, any>>;

export function CheckUpdate(arg1:number):Promise<string>;

export function ClsCalendar():Promise<Array<any>>;

export function CompareFunds(arg1:portfolio.FundCompareQuery):Promise<portfolio.FundCompareResult>;

export function CreateAsset(arg1:asset.Asset):Promise<asset.Asset>;

export function CreateAssetCategory(arg1:asset.AssetCategory):Promise<asset.AssetCategory>;

export function CreateHolding(arg1:portfolio.Holding):Promise<portfolio.Holding>;

export function CreateHouseholdAccount(arg1:asset.HouseholdAccount):Promise<asset.HouseholdAccount>;

export function CreateHouseholdFixedAsset(arg1:asset.HouseholdFixedAsset):Promise<asset.HouseholdFixedAsset>;

export function CreateHouseholdIncome(arg1:asset.HouseholdIncome):Promise<asset.HouseholdIncome>;

export function CreateHouseholdLiability(arg1:asset.HouseholdLiability):Promise<asset.HouseholdLiability>;

export function CreateHouseholdMember(arg1:asset.HouseholdMember):Promise<asset.HouseholdMember>;

export function CreateHouseholdProtection(arg1:asset.HouseholdProtection):Promise<asset.HouseholdProtection>;

export function CreateQuantCategory(arg1:quant.TemplateCategory):Promise<quant.TemplateCategory>;

export function CreateQuantTemplate(arg1:quant.Template):Promise<quant.Template>;

export function DelPrompt(arg1:number):Promise<string>;

export function DeleteAIResponseResult(arg1:number):Promise<string>;

export function DeleteAiRecommendStocks(arg1:number):Promise<string>;

export function DeleteAllStockInfo(arg1:number):Promise<string>;

export function DeleteAsset(arg1:number):Promise<boolean>;

export function DeleteFundWatchGroup(arg1:string):Promise<string>;

export function DeleteHolding(arg1:number):Promise<boolean>;

export function DeleteHouseholdAccount(arg1:number):Promise<boolean>;

export function DeleteHouseholdBenchmark(arg1:number):Promise<boolean>;

export function DeleteHouseholdFixedAsset(arg1:number):Promise<boolean>;

export function DeleteHouseholdIncome(arg1:number):Promise<boolean>;

export function DeleteHouseholdLiability(arg1:number):Promise<boolean>;

export function DeleteHouseholdMember(arg1:number):Promise<boolean>;

export function DeleteHouseholdProtection(arg1:number):Promise<boolean>;

export function DeletePromptTemplate(arg1:number):Promise<string>;

export function DeleteQuantTemplate(arg1:number):Promise<boolean>;

export function DeleteStockChangeHistory(arg1:number):Promise<string>;

export function EMDictCode(arg1:string):Promise<Array<any>>;

export function EnsureFundUniverse():Promise<number>;

export function ExportConfig():Promise<string>;

export function ExportQuantTemplate(arg1:number):Promise<string>;

export function Follow(arg1:string):Promise<string>;

export function FollowFund(arg1:string):Promise<string>;

export function GenerateQuantCode(arg1:quant.GenerateRequest,arg2:number):Promise<Record<string, any>>;

export function GetAIResponseResult(arg1:string):Promise<models.AIResponseResult>;

export function GetAIResponseResultList(arg1:models.AIResponseResultQuery):Promise<models.AIResponseResultPageData>;

export function GetAiConfigs():Promise<Array<data.AIConfig>>;

export function GetAiRecommendStocksList(arg1:models.AiRecommendStocksQuery):Promise<models.AiRecommendStocksPageData>;

export function GetAllConcepts():Promise<Array<string>>;

export function GetAllHoldings():Promise<Array<portfolio.Holding>>;

export function GetAllIndustries():Promise<Array<string>>;

export function GetAllMarkets():Promise<Array<string>>;

export function GetAllStockChangesWithPaging(arg1:number):Promise<data.StockChangesResponse>;

export function GetAllStockInfoById(arg1:number):Promise<models.AllStockInfo>;

export function GetAllStockInfoList(arg1:data.AllStockInfoQuery):Promise<data.AllStockInfoPageData>;

export function GetAllStocks(arg1:number,arg2:number,arg3:string,arg4:models.TechnicalIndicators):Promise<models.AllStocksResp>;

export function GetAssetCategories():Promise<Array<asset.AssetCategory>>;

export function GetAssetSummary():Promise<asset.AssetSummary>;

export function GetAssets():Promise<Array<asset.Asset>>;

export function GetAssetsByType(arg1:string):Promise<Array<asset.Asset>>;

export function GetBetterFunds(arg1:portfolio.BetterFundQuery):Promise<portfolio.BetterFundResult>;

export function GetConfig():Promise<data.SettingConfig>;

export function GetFollowList(arg1:number):Promise<any>;

export function GetFollowedFund():Promise<Array<data.FollowedFund>>;

export function GetFundPortfolioDashboard():Promise<portfolio.FundPortfolioDashboard>;

export function GetFundProfile(arg1:string):Promise<portfolio.FundProfile>;

export function GetFundRecommendationRefreshStatus(arg1:boolean):Promise<portfolio.FundRecommendationRefreshStatus>;

export function GetFundScreener(arg1:portfolio.FundScreenerQuery):Promise<portfolio.FundScreenerResult>;

export function GetGroupList():Promise<Array<data.Group>>;

export function GetHoldingsByType(arg1:string):Promise<Array<portfolio.Holding>>;

export function GetHotStrategy():Promise<Record<string, any>>;

export function GetHouseholdAccounts():Promise<Array<asset.HouseholdAccount>>;

export function GetHouseholdBenchmarks(arg1:string):Promise<Array<asset.HouseholdBenchmarkRecord>>;

export function GetHouseholdDashboardSummary():Promise<asset.HouseholdDashboardSummary>;

export function GetHouseholdFixedAssets():Promise<Array<asset.HouseholdFixedAsset>>;

export function GetHouseholdIncomes():Promise<Array<asset.HouseholdIncome>>;

export function GetHouseholdLiabilities():Promise<Array<asset.HouseholdLiability>>;

export function GetHouseholdLiabilitySchedules(arg1:number):Promise<Array<asset.HouseholdLiabilitySchedule>>;

export function GetHouseholdLiabilityTrend(arg1:number,arg2:number):Promise<Array<asset.HouseholdLiabilityTrendPoint>>;

export function GetHouseholdLiquidAssetDistribution():Promise<Array<asset.HouseholdLiquidAssetDistributionItem>>;

export function GetHouseholdLiquidAssetTrend(arg1:number):Promise<Array<asset.HouseholdLiquidAssetTrendPoint>>;

export function GetHouseholdMembers():Promise<Array<asset.HouseholdMember>>;

export function GetHouseholdProfile():Promise<asset.HouseholdProfile>;

export function GetHouseholdProtections():Promise<Array<asset.HouseholdProtection>>;

export function GetHouseholdSnapshots(arg1:number):Promise<Array<asset.HouseholdSnapshot>>;

export function GetIndustryMoneyRankSina(arg1:string,arg2:string):Promise<Array<Record<string, any>>>;

export function GetIndustryRank(arg1:string,arg2:number):Promise<Array<any>>;

export function GetLatestHouseholdAIAnalysis():Promise<asset.HouseholdAIAnalysis>;

export function GetLatestPortfolioExpectationAIAnalysis():Promise<portfolio.PortfolioExpectationAIAnalysis>;

export function GetMoneyRankSina(arg1:string):Promise<Array<Record<string, any>>>;

export function GetPortfolioExpectationSummary():Promise<portfolio.PortfolioExpectationSummary>;

export function GetPortfolioSummary():Promise<portfolio.PortfolioSummary>;

export function GetProfitHistory(arg1:number):Promise<Array<portfolio.ProfitSnapshot>>;

export function GetPromptTemplateList(arg1:models.PromptTemplateQuery):Promise<models.PromptTemplatePageData>;

export function GetPromptTemplates(arg1:string,arg2:string):Promise<any>;

export function GetQuantCategories():Promise<Array<quant.TemplateCategory>>;

export function GetQuantTagTaxonomy():Promise<Array<quant.TagGroup>>;

export function GetQuantTemplate(arg1:number):Promise<quant.Template>;

export function GetQuantTemplates(arg1:number,arg2:string,arg3:number,arg4:number):Promise<Array<quant.Template>|number>;

export function GetSponsorInfo():Promise<Record<string, any>>;

export function GetStockChangeHistory(arg1:models.StockChangeHistoryQuery):Promise<models.StockChangeHistoryPageData>;

export function GetStockChanges(arg1:Array<number>,arg2:number,arg3:number):Promise<data.StockChangesResponse>;

export function GetStockKLine(arg1:string,arg2:string,arg3:number):Promise<any>;

export function GetStockList(arg1:string):Promise<Array<data.StockBasic>>;

export function GetStockMinutePriceLineData(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetStockMoneyTrendByDay(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function GetTelegraphList(arg1:string):Promise<any>;

export function GetTransactions(arg1:string,arg2:number,arg3:number):Promise<Array<portfolio.Transaction>|number>;

export function GetVersionInfo():Promise<models.VersionInfo>;

export function GetfundList(arg1:string):Promise<Array<data.FundBasic>>;

export function GlobalStockIndexes():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<data.StockInfo>;

export function HotEvent(arg1:number):Promise<any>;

export function HotStock(arg1:string):Promise<any>;

export function HotTopic(arg1:number):Promise<Array<any>>;

export function IndustryResearchReport(arg1:string):Promise<Array<any>>;

export function InitializeGroupSort():Promise<boolean>;

export function InvestCalendarTimeLine(arg1:string):Promise<Array<any>>;

export function LongTigerRank(arg1:string):Promise<any>;

export function NewChatStream(arg1:string,arg2:string,arg3:string,arg4:number,arg5:any,arg6:boolean,arg7:boolean):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function ReFleshTelegraphList(arg1:string):Promise<any>;

export function RebuildHouseholdLiabilitySchedule(arg1:number):Promise<boolean>;

export function RefreshFundProfile(arg1:string):Promise<portfolio.FundProfile>;

export function RefreshFundScreenerData(arg1:number):Promise<Record<string, any>>;

export function RemoveGroup(arg1:number):Promise<string>;

export function RemoveStockGroup(arg1:string,arg2:string,arg3:number):Promise<string>;

export function RenameFundWatchGroup(arg1:string,arg2:string):Promise<string>;

export function RunHouseholdAIAnalysis(arg1:string,arg2:number,arg3:number,arg4:string):Promise<Record<string, any>>;

export function RunPortfolioExpectationAIAnalysis(arg1:number,arg2:number,arg3:string):Promise<Record<string, any>>;

export function SaveAIResponseResult(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function SaveAsMarkdown(arg1:string,arg2:string):Promise<string>;

export function SaveHouseholdSnapshot(arg1:string):Promise<asset.HouseholdSnapshot>;

export function SaveImage(arg1:string,arg2:string):Promise<string>;

export function SavePortfolioSnapshot():Promise<portfolio.ProfitSnapshot>;

export function SaveStockChangesToHistory(arg1:Array<number>):Promise<string>;

export function SaveWordFile(arg1:string,arg2:string):Promise<string>;

export function SearchQuantScriptsWithAI(arg1:quant.ScriptSearchRequest,arg2:number):Promise<Record<string, any>>;

export function SearchStock(arg1:string):Promise<Record<string, any>>;

export function SendDingDingMessageByType(arg1:string,arg2:string,arg3:number):Promise<string>;

export function SendLocalNotification(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function SetAlarmChangePercent(arg1:number,arg2:number,arg3:string):Promise<string>;

export function SetCostPriceAndVolume(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SetStockAICron(arg1:string,arg2:string):Promise<void>;

export function SetStockSort(arg1:number,arg2:string):Promise<void>;

export function ShareAnalysis(arg1:string,arg2:string):Promise<string>;

export function StockNotice(arg1:string):Promise<Array<any>>;

export function StockResearchReport(arg1:string):Promise<Array<any>>;

export function SummaryStockNews(arg1:string,arg2:number,arg3:any,arg4:boolean,arg5:boolean):Promise<void>;

export function SyncPortfolioQuotes():Promise<portfolio.PortfolioSummary>;

export function TestAIConfigConnection(arg1:data.AIConfig):Promise<Record<string, any>>;

export function UnFollow(arg1:string):Promise<string>;

export function UnFollowFund(arg1:string):Promise<string>;

export function UpdateAsset(arg1:asset.Asset):Promise<asset.Asset>;

export function UpdateConfig(arg1:data.SettingConfig):Promise<string>;

export function UpdateFundWatchGroup(arg1:string,arg2:string):Promise<string>;

export function UpdateGroupSort(arg1:number,arg2:number):Promise<boolean>;

export function UpdateHolding(arg1:portfolio.Holding):Promise<portfolio.Holding>;

export function UpdateHouseholdAccount(arg1:asset.HouseholdAccount):Promise<asset.HouseholdAccount>;

export function UpdateHouseholdFixedAsset(arg1:asset.HouseholdFixedAsset):Promise<asset.HouseholdFixedAsset>;

export function UpdateHouseholdIncome(arg1:asset.HouseholdIncome):Promise<asset.HouseholdIncome>;

export function UpdateHouseholdLiability(arg1:asset.HouseholdLiability):Promise<asset.HouseholdLiability>;

export function UpdateHouseholdMember(arg1:asset.HouseholdMember):Promise<asset.HouseholdMember>;

export function UpdateHouseholdProtection(arg1:asset.HouseholdProtection):Promise<asset.HouseholdProtection>;

export function UpdatePromptTemplate(arg1:models.PromptTemplate):Promise<string>;

export function UpdateQuantTemplate(arg1:quant.Template):Promise<quant.Template>;

export function UpsertFundHoldingByAmount(arg1:portfolio.FundPositionInput):Promise<portfolio.Holding>;

export function UpsertHouseholdBenchmark(arg1:asset.HouseholdBenchmarkRecord):Promise<asset.HouseholdBenchmarkRecord>;

export function UpsertHouseholdProfile(arg1:asset.HouseholdProfile):Promise<asset.HouseholdProfile>;

export function VerifyAssetUnlockPassword(arg1:string):Promise<boolean>;
