// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateQuantTemplate(arg1) {
  return window['go']['main']['App']['ActivateQuantTemplate'](arg1);
}

export function AddAllStockInfo(arg1) {
  return window['go']['main']['App']['AddAllStockInfo'](arg1);
}

export function AddGroup(arg1) {
  return window['go']['main']['App']['AddGroup'](arg1);
}

export function AddPrompt(arg1) {
  return window['go']['main']['App']['AddPrompt'](arg1);
}

export function AddPromptTemplate(arg1) {
  return window['go']['main']['App']['AddPromptTemplate'](arg1);
}

export function AddStockGroup(arg1, arg2) {
  return window['go']['main']['App']['AddStockGroup'](arg1, arg2);
}

export function AddTransaction(arg1) {
  return window['go']['main']['App']['AddTransaction'](arg1);
}

export function AnalyzeQuantLinkageWithAI(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeQuantLinkageWithAI'](arg1, arg2);
}

export function AnalyzeSentiment(arg1) {
  return window['go']['main']['App']['AnalyzeSentiment'](arg1);
}

export function AnalyzeSentimentWithFreqWeight(arg1) {
  return window['go']['main']['App']['AnalyzeSentimentWithFreqWeight'](arg1);
}

export function BatchDeleteAllStockInfo(arg1) {
  return window['go']['main']['App']['BatchDeleteAllStockInfo'](arg1);
}

export function BuildQuantPrompt(arg1) {
  return window['go']['main']['App']['BuildQuantPrompt'](arg1);
}

export function BuildQuantScriptSearchLinks(arg1) {
  return window['go']['main']['App']['BuildQuantScriptSearchLinks'](arg1);
}

export function ChatWithAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChatWithAgent'](arg1, arg2, arg3);
}

export function ChatWithHouseholdDigitalAnalysis(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChatWithHouseholdDigitalAnalysis'](arg1, arg2, arg3, arg4);
}

export function CheckSponsorCode(arg1) {
  return window['go']['main']['App']['CheckSponsorCode'](arg1);
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function ClsCalendar() {
  return window['go']['main']['App']['ClsCalendar']();
}

export function CreateAsset(arg1) {
  return window['go']['main']['App']['CreateAsset'](arg1);
}

export function CreateAssetCategory(arg1) {
  return window['go']['main']['App']['CreateAssetCategory'](arg1);
}

export function CreateHolding(arg1) {
  return window['go']['main']['App']['CreateHolding'](arg1);
}

export function CreateHouseholdAccount(arg1) {
  return window['go']['main']['App']['CreateHouseholdAccount'](arg1);
}

export function CreateHouseholdFixedAsset(arg1) {
  return window['go']['main']['App']['CreateHouseholdFixedAsset'](arg1);
}

export function CreateHouseholdIncome(arg1) {
  return window['go']['main']['App']['CreateHouseholdIncome'](arg1);
}

export function CreateHouseholdLiability(arg1) {
  return window['go']['main']['App']['CreateHouseholdLiability'](arg1);
}

export function CreateHouseholdMember(arg1) {
  return window['go']['main']['App']['CreateHouseholdMember'](arg1);
}

export function CreateHouseholdProtection(arg1) {
  return window['go']['main']['App']['CreateHouseholdProtection'](arg1);
}

export function CreateQuantCategory(arg1) {
  return window['go']['main']['App']['CreateQuantCategory'](arg1);
}

export function CreateQuantTemplate(arg1) {
  return window['go']['main']['App']['CreateQuantTemplate'](arg1);
}

export function DelPrompt(arg1) {
  return window['go']['main']['App']['DelPrompt'](arg1);
}

export function DeleteAIResponseResult(arg1) {
  return window['go']['main']['App']['DeleteAIResponseResult'](arg1);
}

export function DeleteAiRecommendStocks(arg1) {
  return window['go']['main']['App']['DeleteAiRecommendStocks'](arg1);
}

export function DeleteAllStockInfo(arg1) {
  return window['go']['main']['App']['DeleteAllStockInfo'](arg1);
}

export function DeleteAsset(arg1) {
  return window['go']['main']['App']['DeleteAsset'](arg1);
}

export function DeleteHolding(arg1) {
  return window['go']['main']['App']['DeleteHolding'](arg1);
}

export function DeleteHouseholdAccount(arg1) {
  return window['go']['main']['App']['DeleteHouseholdAccount'](arg1);
}

export function DeleteHouseholdBenchmark(arg1) {
  return window['go']['main']['App']['DeleteHouseholdBenchmark'](arg1);
}

export function DeleteHouseholdFixedAsset(arg1) {
  return window['go']['main']['App']['DeleteHouseholdFixedAsset'](arg1);
}

export function DeleteHouseholdIncome(arg1) {
  return window['go']['main']['App']['DeleteHouseholdIncome'](arg1);
}

export function DeleteHouseholdLiability(arg1) {
  return window['go']['main']['App']['DeleteHouseholdLiability'](arg1);
}

export function DeleteHouseholdMember(arg1) {
  return window['go']['main']['App']['DeleteHouseholdMember'](arg1);
}

export function DeleteHouseholdProtection(arg1) {
  return window['go']['main']['App']['DeleteHouseholdProtection'](arg1);
}

export function DeletePromptTemplate(arg1) {
  return window['go']['main']['App']['DeletePromptTemplate'](arg1);
}

export function DeleteQuantTemplate(arg1) {
  return window['go']['main']['App']['DeleteQuantTemplate'](arg1);
}

export function EMDictCode(arg1) {
  return window['go']['main']['App']['EMDictCode'](arg1);
}

export function ExportConfig() {
  return window['go']['main']['App']['ExportConfig']();
}

export function ExportQuantTemplate(arg1) {
  return window['go']['main']['App']['ExportQuantTemplate'](arg1);
}

export function Follow(arg1) {
  return window['go']['main']['App']['Follow'](arg1);
}

export function FollowFund(arg1) {
  return window['go']['main']['App']['FollowFund'](arg1);
}

export function GenerateQuantCode(arg1, arg2) {
  return window['go']['main']['App']['GenerateQuantCode'](arg1, arg2);
}

export function GetAIResponseResult(arg1) {
  return window['go']['main']['App']['GetAIResponseResult'](arg1);
}

export function GetAIResponseResultList(arg1) {
  return window['go']['main']['App']['GetAIResponseResultList'](arg1);
}

export function GetAiConfigs() {
  return window['go']['main']['App']['GetAiConfigs']();
}

export function GetAiRecommendStocksList(arg1) {
  return window['go']['main']['App']['GetAiRecommendStocksList'](arg1);
}

export function GetAllConcepts() {
  return window['go']['main']['App']['GetAllConcepts']();
}

export function GetAllHoldings() {
  return window['go']['main']['App']['GetAllHoldings']();
}

export function GetAllIndustries() {
  return window['go']['main']['App']['GetAllIndustries']();
}

export function GetAllMarkets() {
  return window['go']['main']['App']['GetAllMarkets']();
}

export function GetAllStockInfoById(arg1) {
  return window['go']['main']['App']['GetAllStockInfoById'](arg1);
}

export function GetAllStockInfoList(arg1) {
  return window['go']['main']['App']['GetAllStockInfoList'](arg1);
}

export function GetAllStocks(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetAllStocks'](arg1, arg2, arg3, arg4);
}

export function GetAssetCategories() {
  return window['go']['main']['App']['GetAssetCategories']();
}

export function GetAssetSummary() {
  return window['go']['main']['App']['GetAssetSummary']();
}

export function GetAssets() {
  return window['go']['main']['App']['GetAssets']();
}

export function GetAssetsByType(arg1) {
  return window['go']['main']['App']['GetAssetsByType'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFollowList(arg1) {
  return window['go']['main']['App']['GetFollowList'](arg1);
}

export function GetFollowedFund() {
  return window['go']['main']['App']['GetFollowedFund']();
}

export function GetGroupList() {
  return window['go']['main']['App']['GetGroupList']();
}

export function GetHoldingsByType(arg1) {
  return window['go']['main']['App']['GetHoldingsByType'](arg1);
}

export function GetHotStrategy() {
  return window['go']['main']['App']['GetHotStrategy']();
}

export function GetHouseholdAccounts() {
  return window['go']['main']['App']['GetHouseholdAccounts']();
}

export function GetHouseholdBenchmarks(arg1) {
  return window['go']['main']['App']['GetHouseholdBenchmarks'](arg1);
}

export function GetHouseholdDashboardSummary() {
  return window['go']['main']['App']['GetHouseholdDashboardSummary']();
}

export function GetHouseholdFixedAssets() {
  return window['go']['main']['App']['GetHouseholdFixedAssets']();
}

export function GetHouseholdIncomes() {
  return window['go']['main']['App']['GetHouseholdIncomes']();
}

export function GetHouseholdLiabilities() {
  return window['go']['main']['App']['GetHouseholdLiabilities']();
}

export function GetHouseholdLiabilitySchedules(arg1) {
  return window['go']['main']['App']['GetHouseholdLiabilitySchedules'](arg1);
}

export function GetHouseholdLiabilityTrend(arg1, arg2) {
  return window['go']['main']['App']['GetHouseholdLiabilityTrend'](arg1, arg2);
}

export function GetHouseholdLiquidAssetDistribution() {
  return window['go']['main']['App']['GetHouseholdLiquidAssetDistribution']();
}

export function GetHouseholdLiquidAssetTrend(arg1) {
  return window['go']['main']['App']['GetHouseholdLiquidAssetTrend'](arg1);
}

export function GetHouseholdMembers() {
  return window['go']['main']['App']['GetHouseholdMembers']();
}

export function GetHouseholdProfile() {
  return window['go']['main']['App']['GetHouseholdProfile']();
}

export function GetHouseholdProtections() {
  return window['go']['main']['App']['GetHouseholdProtections']();
}

export function GetHouseholdSnapshots(arg1) {
  return window['go']['main']['App']['GetHouseholdSnapshots'](arg1);
}

export function GetIndustryMoneyRankSina(arg1, arg2) {
  return window['go']['main']['App']['GetIndustryMoneyRankSina'](arg1, arg2);
}

export function GetIndustryRank(arg1, arg2) {
  return window['go']['main']['App']['GetIndustryRank'](arg1, arg2);
}

export function GetLatestHouseholdAIAnalysis() {
  return window['go']['main']['App']['GetLatestHouseholdAIAnalysis']();
}

export function GetMoneyRankSina(arg1) {
  return window['go']['main']['App']['GetMoneyRankSina'](arg1);
}

export function GetPortfolioSummary() {
  return window['go']['main']['App']['GetPortfolioSummary']();
}

export function GetProfitHistory(arg1) {
  return window['go']['main']['App']['GetProfitHistory'](arg1);
}

export function GetPromptTemplateList(arg1) {
  return window['go']['main']['App']['GetPromptTemplateList'](arg1);
}

export function GetPromptTemplates(arg1, arg2) {
  return window['go']['main']['App']['GetPromptTemplates'](arg1, arg2);
}

export function GetQuantCategories() {
  return window['go']['main']['App']['GetQuantCategories']();
}

export function GetQuantTagTaxonomy() {
  return window['go']['main']['App']['GetQuantTagTaxonomy']();
}

export function GetQuantTemplate(arg1) {
  return window['go']['main']['App']['GetQuantTemplate'](arg1);
}

export function GetQuantTemplates(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetQuantTemplates'](arg1, arg2, arg3, arg4);
}

export function GetSponsorInfo() {
  return window['go']['main']['App']['GetSponsorInfo']();
}

export function GetStockKLine(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetStockKLine'](arg1, arg2, arg3);
}

export function GetStockList(arg1) {
  return window['go']['main']['App']['GetStockList'](arg1);
}

export function GetStockMinutePriceLineData(arg1, arg2) {
  return window['go']['main']['App']['GetStockMinutePriceLineData'](arg1, arg2);
}

export function GetStockMoneyTrendByDay(arg1, arg2) {
  return window['go']['main']['App']['GetStockMoneyTrendByDay'](arg1, arg2);
}

export function GetTelegraphList(arg1) {
  return window['go']['main']['App']['GetTelegraphList'](arg1);
}

export function GetTransactions(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTransactions'](arg1, arg2, arg3);
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function GetfundList(arg1) {
  return window['go']['main']['App']['GetfundList'](arg1);
}

export function GlobalStockIndexes() {
  return window['go']['main']['App']['GlobalStockIndexes']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HotEvent(arg1) {
  return window['go']['main']['App']['HotEvent'](arg1);
}

export function HotStock(arg1) {
  return window['go']['main']['App']['HotStock'](arg1);
}

export function HotTopic(arg1) {
  return window['go']['main']['App']['HotTopic'](arg1);
}

export function IndustryResearchReport(arg1) {
  return window['go']['main']['App']['IndustryResearchReport'](arg1);
}

export function InitializeGroupSort() {
  return window['go']['main']['App']['InitializeGroupSort']();
}

export function InvestCalendarTimeLine(arg1) {
  return window['go']['main']['App']['InvestCalendarTimeLine'](arg1);
}

export function LongTigerRank(arg1) {
  return window['go']['main']['App']['LongTigerRank'](arg1);
}

export function NewChatStream(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['NewChatStream'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ReFleshTelegraphList(arg1) {
  return window['go']['main']['App']['ReFleshTelegraphList'](arg1);
}

export function RebuildHouseholdLiabilitySchedule(arg1) {
  return window['go']['main']['App']['RebuildHouseholdLiabilitySchedule'](arg1);
}

export function RemoveGroup(arg1) {
  return window['go']['main']['App']['RemoveGroup'](arg1);
}

export function RemoveStockGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['RemoveStockGroup'](arg1, arg2, arg3);
}

export function RunHouseholdAIAnalysis(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunHouseholdAIAnalysis'](arg1, arg2, arg3, arg4);
}

export function SaveAIResponseResult(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveAIResponseResult'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SaveAsMarkdown(arg1, arg2) {
  return window['go']['main']['App']['SaveAsMarkdown'](arg1, arg2);
}

export function SaveHouseholdSnapshot(arg1) {
  return window['go']['main']['App']['SaveHouseholdSnapshot'](arg1);
}

export function SaveImage(arg1, arg2) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2);
}

export function SaveWordFile(arg1, arg2) {
  return window['go']['main']['App']['SaveWordFile'](arg1, arg2);
}

export function SearchQuantScriptsWithAI(arg1, arg2) {
  return window['go']['main']['App']['SearchQuantScriptsWithAI'](arg1, arg2);
}

export function SearchStock(arg1) {
  return window['go']['main']['App']['SearchStock'](arg1);
}

export function SendDingDingMessageByType(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendDingDingMessageByType'](arg1, arg2, arg3);
}

export function SendLocalNotification(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendLocalNotification'](arg1, arg2, arg3);
}

export function SetAlarmChangePercent(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetAlarmChangePercent'](arg1, arg2, arg3);
}

export function SetCostPriceAndVolume(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCostPriceAndVolume'](arg1, arg2, arg3);
}

export function SetStockAICron(arg1, arg2) {
  return window['go']['main']['App']['SetStockAICron'](arg1, arg2);
}

export function SetStockSort(arg1, arg2) {
  return window['go']['main']['App']['SetStockSort'](arg1, arg2);
}

export function ShareAnalysis(arg1, arg2) {
  return window['go']['main']['App']['ShareAnalysis'](arg1, arg2);
}

export function StockNotice(arg1) {
  return window['go']['main']['App']['StockNotice'](arg1);
}

export function StockResearchReport(arg1) {
  return window['go']['main']['App']['StockResearchReport'](arg1);
}

export function SummaryStockNews(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SummaryStockNews'](arg1, arg2, arg3, arg4, arg5);
}

export function TestAIConfigConnection(arg1) {
  return window['go']['main']['App']['TestAIConfigConnection'](arg1);
}

export function UnFollow(arg1) {
  return window['go']['main']['App']['UnFollow'](arg1);
}

export function UnFollowFund(arg1) {
  return window['go']['main']['App']['UnFollowFund'](arg1);
}

export function UpdateAsset(arg1) {
  return window['go']['main']['App']['UpdateAsset'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateGroupSort(arg1, arg2) {
  return window['go']['main']['App']['UpdateGroupSort'](arg1, arg2);
}

export function UpdateHolding(arg1) {
  return window['go']['main']['App']['UpdateHolding'](arg1);
}

export function UpdateHouseholdAccount(arg1) {
  return window['go']['main']['App']['UpdateHouseholdAccount'](arg1);
}

export function UpdateHouseholdFixedAsset(arg1) {
  return window['go']['main']['App']['UpdateHouseholdFixedAsset'](arg1);
}

export function UpdateHouseholdIncome(arg1) {
  return window['go']['main']['App']['UpdateHouseholdIncome'](arg1);
}

export function UpdateHouseholdLiability(arg1) {
  return window['go']['main']['App']['UpdateHouseholdLiability'](arg1);
}

export function UpdateHouseholdMember(arg1) {
  return window['go']['main']['App']['UpdateHouseholdMember'](arg1);
}

export function UpdateHouseholdProtection(arg1) {
  return window['go']['main']['App']['UpdateHouseholdProtection'](arg1);
}

export function UpdatePromptTemplate(arg1) {
  return window['go']['main']['App']['UpdatePromptTemplate'](arg1);
}

export function UpdateQuantTemplate(arg1) {
  return window['go']['main']['App']['UpdateQuantTemplate'](arg1);
}

export function UpsertHouseholdBenchmark(arg1) {
  return window['go']['main']['App']['UpsertHouseholdBenchmark'](arg1);
}

export function UpsertHouseholdProfile(arg1) {
  return window['go']['main']['App']['UpsertHouseholdProfile'](arg1);
}

export function VerifyAssetUnlockPassword(arg1) {
  return window['go']['main']['App']['VerifyAssetUnlockPassword'](arg1);
}
